# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    deps: [check]

  check:
    - task: tests
    - task: type
    - task: lint
    - task: fmtchk
    - git diff --exit-code

  fix: "{{.RUN}} ruff check --fix {{.CLI_ARGS}}"
  fmt: "{{.RUN}} yapf -ir -vv . {{.CLI_ARGS}}"
  fmtchk: "{{.RUN}} yapf -qr -vv . {{.CLI_ARGS}}"
  lint: "{{.RUN}} ruff check {{.CLI_ARGS}}"
  test:
    deps: [download]
    cmds:
      - "{{.RUN}} pytest {{.PYTEST}} {{.CLI_ARGS}}"
  tests:
    deps: [download]
    cmds:
      - "{{.RUN}} tox {{.TOX}} {{.CLI_ARGS}}"
  type: "{{.RUN}} pyrefly check {{.PYREFLY}} {{.CLI_ARGS}}"

  download:
    generates:
      - fonts/NotoSansCJKjp-Regular.otf
    cmds:
      - "{{.RUN}} python3 ./tests/download_fonts.py"

  install-git-hooks:
    desc: Create git hooks
    cmds:
      - echo '#!/bin/sh' > .git/hooks/pre-push
      - echo 'task check' >> .git/hooks/pre-push
      - cmd: chmod +x .git/hooks/pre-push
        platforms: [linux, darwin]

vars:
  PYREFLY: --summarize-errors
  PYTEST: -v
  RUN: uv run
  TOX: -p
